# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine poetry
    - name: Build Package
      run: |
        python -m poetry build
    - name: Push release
    - uses: actions/upload-artifact@v2
      with:
        name: azfunctionsmonitor
        path: dist/
    
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m poetry build
        python -m poetry publish --username ${{ secrets.PYPI_USERNAME }} --password "${{ secrets.PYPI_PASSWORD }}"
        # twine upload dist/*
